name: Feature request
description: Request a feature
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
  - type: textarea
    attributes:
      label: Proposed solution
